Repository CECOM-CAU/CECOM_Web_BE, pull requests merged in 2023-03, with the labels that each got.

#8 [DEV] 기본 API Route 구성
  src/Routes/AboutRouter.ts
  src/Routes/ActivityRouter.ts
  src/Routes/ProjectRouter.ts
  src/index.ts
Labels: dev

#9 [DEV] 함수 DOCS 폴더 생성
  docs/getStaffList.md
Labels: documentation

#11 UPDATE: update readme.md
  README.md
Labels: documentation

#16 [DEV] AboutRouter.ts post 함수 개발
  docs/getData.md
  docs/getList.md
  package-lock.json
  package.json
  src/Routes/AboutRouter.ts
  src/index.ts
Labels: dev

#19 [DEV] Firebase Util 구성
  package-lock.json
  package.json
  src/Utils/FirebaseUtil.ts
Labels: dev

#20 [DEV] FirebaseUtil 의 getFirebaseDBlist 수정 + getStaffList.md의 json구조 변경
  docs/getStaffList.md
  src/Routes/AboutRouter.ts
  src/Utils/FirebaseUtil.ts
  src/index.ts
Labels: documentation, dev

#21 [DEV]: 내가 맡은 부분 다 끝냄
  docs/getData.md
  docs/getList.md
  src/Routes/AboutRouter.ts
  src/Routes/ActivityRouter.ts
  src/Routes/ProjectRouter.ts
  src/Utils/FirebaseUtil.ts
Labels: documentation, enhancement, dev

#23 [DEV] 최종 리팩토링
  docs/getData.md
  docs/getList.md
  docs/getStaffList.md
  src/Routes/AboutRouter.ts
  src/Routes/ActivityRouter.ts
  src/Routes/ProjectRouter.ts
  src/Utils/FirebaseUtil.ts
  src/index.ts
Labels: enhancement

#25 [FIX] JSON / UrlEncoded 옵션 누락
  src/index.ts
Labels: bug
